default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: andru
  password: duft1992

development:
  <<: *default
  host: localhost
  database: survey_app

test:
  <<: *default
  host: localhost
  database: survey_app_test